server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: cms@alexengrig
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true